services:
  - type: web
    name: admin-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
